env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/vue3-essential
  - airbnb-base
ignorePatterns:
  - docs/**/*.js
  - src/plugins/**/*.js
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules:
  'import/no-unresolved': off
  'import/extensions': off
  'no-console': off
